add CI&CD workflow
devrel-kr/nhn-toast-notification-service-custom-connector pull request #15
Opened 2022-04-15 20:24 UTC by KIMTHE

- CI&CD pipeline 
    - tag push trigger
    - (setup)-bulid-(test)-create artifacts-upload artifact
    - download artifact-(create release)-(create zip files)-deploy artifacts in github release

- function apps 경로(sms, verification sms)를 하드코딩으로 구현했습니다.

2022-04-15 20:27 UTC, KIMTHE commented
bicep workflow 작성은 다음회의 이후에 진행되는건가요?

2022-04-16 01:29 UTC, justinyoo requested changes
몇가지 코멘트를 남겨 뒀습니다. 확인해 보세욥!

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +        type: string
이 `workflow_dispatch` 이벤트가 필요한가요? 필요 없으면 빼셔도 좋습니다.

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +      - '**'
보통 태그를 통해 아티팩트를 릴리즈하니까 태그 기준을 한 번 잡죠. [시만틱 버저닝](https://semver.org/)의 형태를 가장 널리 따라갑니다. 즉 우리가 버전을 잡을 때 `v1.0.0` 같은 형식으로 한다고 생각한다면, `**` 보다는 `v*` 형태로 잡아주는 것이 좋습니다.

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +          dotnet-version: 6.0.x
버전을 가장 최신의 6.x 것으로 가져오는 것이 좋으니 `6.0.x` 대신 `6.x`로 하시면 좋습니다.

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +      - name: Upload app1 artifact
`app1` 대신 좀 더 의미이 있는 이름을 주면 좋겠습니다.

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +      - name: Upload app2 artifact
`app2` 대신 좀 더 의미이 있는 이름을 주면 좋겠습니다.

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +        uses: actions/download-artifact@v3
오, 이렇게 하면 업로드한 아티팩트 모두를 한번에 다운로드 받을 수 있나요?

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +      - run: zip ${{env.SMS_VERIFICATION_PUBLISH_NAME}}.zip ${{env.SMS_VERIFICATION_PUBLISH_NAME}}
혹시 이 zip 파일들을 그대로 애저 펑션 앱에 배포할 수 있는지 확인해 보셨나요? 이건 윈도우에서는 확인할 수 없으니 WSL 같은 걸로 확인해 보시면 좋겠습니다.

2022-04-16 01:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +          release_name: Release ${{ github.ref }}
혹시 이 때 릴리즈 노트도 추가할 수 있나요?

2022-04-16 01:32 UTC, justinyoo commented
> bicep workflow 작성은 다음회의 이후에 진행되는건가요?

바이셉 워크플로우라는게 깃헙 액션 워크플로우를 말씀하시는 거라면 그건 지금 당장 작성하실 필요는 없구요, 일단 이거 머지되면 지민님이랑 같이 나눠서 바이셉 파일을 만들어 보시죠!

2022-04-16 04:35 UTC, KIMTHE commented
> 몇가지 코멘트를 남겨 뒀습니다. 확인해 보세욥! 실제로 민수님 리포에 가서 보니까 릴리즈가 올라와 있지 않던데 말입니다!

테스트한다고 만든 릴리즈들이 많아서 정리한다고 전부 삭제했습니다

2022-04-16 04:37 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +        type: string
넵 수동으로 테스트해보는 용도였는데, 삭제하겠습니다

2022-04-16 04:38 UTC, KIMTHE commented
> > bicep workflow 작성은 다음회의 이후에 진행되는건가요?
> 
> 바이셉 워크플로우라는게 깃헙 액션 워크플로우를 말씀하시는 거라면 그건 지금 당장 작성하실 필요는 없구요, 일단 이거 머지되면 지민님이랑 같이 나눠서 바이셉 파일을 만들어 보시죠!

알겠습니다!

2022-04-16 06:05 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +        uses: actions/download-artifact@v3
넵 전부 다운로드됩니다.

2022-04-16 06:18 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +          release_name: Release ${{ github.ref }}
하드코딩으로 넣거나, 마크다운문서를 만들어서 경로로 넣을 수 있습니다.

2022-04-16 07:41 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +      - run: zip ${{env.SMS_VERIFICATION_PUBLISH_NAME}}.zip ${{env.SMS_VERIFICATION_PUBLISH_NAME}}
- [ref: Zip deployment for Azure Functions](https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push)

-  일단, 공식문서에서 zip을 배포하는 명령어가 있음을 확인했습니다.

- 하지만, 제가 직접 cli로 시도해봤더니 다음과 같은 오류가 발생하였습니다.

`Toast.Sms: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

![image](https://user-images.githubusercontent.com/29460783/163666520-09f39e08-4e7f-4b49-80cd-0a398d760617.png)

2022-04-16 08:03 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +      - '**'
수정완료했습니다.

2022-04-16 08:03 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +          dotnet-version: 6.0.x
수정완료했습니다.

2022-04-16 08:03 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +      - name: Upload app1 artifact
수정완료했습니다.

2022-04-16 08:03 UTC, KIMTHE commented on .github/workflows/tag.yaml
> +      - name: Upload app2 artifact
수정완료했습니다.

2022-04-16 11:29 UTC, justinyoo commented on .github/workflows/tag.yaml
> +      - run: zip ${{env.SMS_VERIFICATION_PUBLISH_NAME}}.zip ${{env.SMS_VERIFICATION_PUBLISH_NAME}}
저 zip 파일을 압축할 때 디렉토리가 함께 압축이 풀리면 배포해도 에러가 나요. 그래서 저 zip 파일의 구조를 확인해 봐야 합니다.

2022-04-16 11:31 UTC, justinyoo commented
저 zip 파일을 풀면:

* 디렉토리 안에 다시 디렉토리가 들어있고 그 안에 파일이 들어있는 구조인지,
* 디렉토리 안에 파일이 들어있는 구조인지

이걸 확인해 보셔야 합니다. 그러지 않으면 배포하고 나서 에러가 나요.

2022-04-16 17:39 UTC, KIMTHE commented
> 저 zip 파일을 풀면:
> 
> * 디렉토리 안에 다시 디렉토리가 들어있고 그 안에 파일이 들어있는 구조인지,
> * 디렉토리 안에 파일이 들어있는 구조인지
> 
> 이걸 확인해 보셔야 합니다. 그러지 않으면 배포하고 나서 에러가 나요.

`디렉토리 안에 다시 디렉토리가 들어있고 그 안에 파일이 들어있는 구조`

해당 구조가 되도록 zip파일을 만들도록 수정하였습니다.

2022-04-17 00:51 UTC, justinyoo commented
> ![image](https://user-images.githubusercontent.com/29460783/163685787-f297b21e-7355-4499-b1c8-7c2e0f700e17.png)
> 
> `디렉토리 안에 다시 디렉토리가 들어있고 그 안에 파일이 들어있는 구조`
> 
> * 해당 구조가 되도록 zip파일을 만들도록 수정하였습니다.
> 
> 저런 구조로 배포를 시도하였더니, 오류메시지는 뜨지않습니다. 그런데, 포털에서 배포된 함수가 확인이 되지 않습니다. 여러번 배포를 시도하니 확인이 됬다 안됬다가 합니다.

앗, 반대로 하셔야 합니다! ㅠㅠ 디렉토리 바로 밑에 `bin` 디렉토리를 포함한 다른 엔드포인트 디렉토리들이 들어와야 해요. 이렇게 .zip 파일을 만들고 배포해 보시겠어요?

2022-04-17 05:26 UTC, KIMTHE commented
> 앗, 반대로 하셔야 합니다! ㅠㅠ 디렉토리 바로 밑에 `bin` 디렉토리를 포함한 다른 엔드포인트 디렉토리들이 들어와야 해요. 이렇게 .zip 파일을 만들고 배포해 보시겠어요?

`디렉토리 안에 파일이 들어있는 구조`

- 해당 구조의 zip형태로 배포를 시도해봤는데, Azure portal에서 다음과 같은 런타임 오류가 발생하였습니다.
    - Microsoft.Extensions.DependencyInjection, Version=6.0.0.0 이 dependency를 추가하고 시도해봤는데 똑같은 에러가 발생하였습니다.
    - 검색을 해본결과, 비슷한 사례를 보면 어떤 dependency의 호환되지않는 버전때문에 해당 에러가 발생하는것 같습니다. 하지만 이 에러에 대한 해결방법은 찾지 못했습니다.


`Toast.Sms: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection, Version=6.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. The system cannot find the file specified.`

- 아마 이 에러가 해결되면 정상적으로 배포될것같습니다, 커밋완료했습니다.

2022-04-17 07:59 UTC, justinyoo commented
방금 의존성 패키지가 퍼블리시할 때 포함되지 않는 오류를 해결했습니다. main 브랜치 최신으로 업데이트 해 보시고, 다시 한 번 확인해 보시겠어요?

2022-04-17 08:09 UTC, KIMTHE commented
> 방금 의존성 패키지가 퍼블리시할 때 포함되지 않는 오류를 해결했습니다. main 브랜치 최신으로 업데이트 해 보시고, 다시 한 번 확인해 보시겠어요?
![image](https://user-images.githubusercontent.com/29460783/163706193-10418bdf-c9b5-48b0-9a2f-09a5ea71e3e2.png)

넵, 다음과 같이 정상배포되는것을 확인하였습니다!

2022-04-17 08:12 UTC, justinyoo approved these changes
수고하셨습니다!

2022-04-17 08:12 UTC, merged