Bicep code refactoring
devrel-kr/nhn-toast-notification-service-custom-connector pull request #21
Opened 2022-04-27 12:43 UTC by wlals761

main.bicep 추가
- provision-apiManagement.bicep 실행 후 provision-functionApp.bicep 두 번 실행
- provision-functionApp.bicep 두 번 실행할 때 배포명이 같으면 충돌으로 인한 에러가 발생하여 provision-functionApp.bicep파일에서 배포명 뒤에 suffix를 붙였습니다.

2022-04-29 04:55 UTC, justinyoo requested changes
코멘트 남겼는데 확인 좀 부탁 드려요!

2022-04-29 04:55 UTC, justinyoo commented on infra/main.bicep
> +]
이걸 하나로 합쳐서 `suffixes` 로 하고 기본값을 `[ 'sms', 'sms-verify' ]`로 두면 어때요?

2022-04-29 06:23 UTC, wlals761 commented on infra/main.bicep
> +]
수정하였습니다!

2022-04-30 02:16 UTC, justinyoo approved these changes
좋네요! 수고하셨습니다!

2022-04-30 02:16 UTC, justinyoo commented on infra/main.bicep
> +]
그렇게 하면 배시 셸에서는 아래와 같은 식으로 배열값을 파라미터로 넘길 수 있습니다.

```bash
az deployment group create \
  --resource-group testgroup \
  --template-file <path-to-bicep> \
  --parameters exampleString='inline string' exampleArray='("value1", "value2")'
```

2022-04-30 02:17 UTC, merged