Refactor workflow with issue
devrel-kr/nhn-toast-notification-service-custom-connector pull request #27
Opened 2022-05-01 13:13 UTC by KIMTHE

- #26 

- [strategy-matrix](https://github.community/t/reusable-workflow-with-strategy-matrix/205676/2)을 이용하여, 동적으로 함수명을 받아서 CI&CD 수행함 

- release to azure 전에, 먼저 함수 폴더명과 매칭되는 함수 앱 리소스를 리소스그룹에 배포해야한다.

2022-05-01 22:32 UTC, justinyoo commented
질문: 저~기 위에 보면 수많은 커밋 히스토리들이 보이는데, 어떻게 하면 저게 딸려오나요?

2022-05-02 02:03 UTC, KIMTHE commented
> 질문: 저~기 위에 보면 수많은 커밋 히스토리들이 보이는데, 어떻게 하면 저게 딸려오나요?

저도 잘 모르겠습니다. 멘토님이 수정한 커밋을 pull을 제대로 받지않은상태에서 새 브랜치를 판 후, 수정을 하고 처음에 PR을 넣으니 conflict가 떳는데, 이를 해결한 후 merge가 되고, 그것을 pull을 받게되는 과정에서 이상하게 된것 같습니다.

아예 브랜치 재생성해서 수정한 파일 덮어씌우고, 다시 PR을 넣는게 좋을까요?

2022-05-03 02:52 UTC, justinyoo requested changes
전반적으로 깃헙에 릴리즈 하는 부분과 애저에 배포하는 부분이 한데 뒤섞여 있어서 혼란스러운데, workflow_call 을 깃헙 릴리즈 하는 것과 애저 배포하는 걸 따로 구분하면 어때요?

2022-05-03 02:52 UTC, justinyoo commented on .github/workflows/continuous-deployment.yaml
> +        default: '{"include":[{"src-path":"Sms","fncapp-name":"sms"},{"src-path":"Sms.Verification","fncapp-name":"sms-verify"}]}'
`required: true` 가 된다면 `default: ...` 부분이 필요가 없습니다.

2022-05-03 02:52 UTC, justinyoo commented on .github/workflows/continuous-deployment.yaml
> +      TOKEN:
이건 `GITHUB_TOKEN`과 같이 가시죠.

2022-05-03 06:47 UTC, KIMTHE commented on .github/workflows/continuous-deployment.yaml
> +        default: '{"include":[{"src-path":"Sms","fncapp-name":"sms"},{"src-path":"Sms.Verification","fncapp-name":"sms-verify"}]}'
수정완료했습니다.

2022-05-03 06:49 UTC, KIMTHE commented on .github/workflows/continuous-deployment.yaml
> +      TOKEN:
![image](https://user-images.githubusercontent.com/29460783/166414251-46f2c9a8-bd16-44bb-aa3f-f0a556c725e3.png)
예약어라 사용할수없다는 에러가 뜹니다.

2022-05-03 06:51 UTC, KIMTHE commented
> 전반적으로 깃헙에 릴리즈 하는 부분과 애저에 배포하는 부분이 한데 뒤섞여 있어서 혼란스러운데, workflow_call 을 깃헙 릴리즈 하는 것과 애저 배포하는 걸 따로 구분하면 어때요?

jobs을 github, azure 배포로 따로 나누면 좋을까요?

2022-05-03 08:28 UTC, justinyoo requested changes
우리 잠시 후에 다시 얘기해 봐요

2022-05-03 08:28 UTC, justinyoo commented on .github/workflows/continuous-deployment.yaml
> +        default: '{"include":[{"src-path":"Sms","fncapp-name":"sms"},{"src-path":"Sms.Verification","fncapp-name":"sms-verify"}]}'
`"include"` 부분이 필요가 없을 거예요. 다시 한 번 확인해 보십쇼.

2022-05-03 08:28 UTC, justinyoo commented on .github/workflows/continuous-deployment.yaml
> +      TOKEN:
https://github.com/devkimchi/ASWA-AutoPilot-Sample/blob/123f75a390a3b94d532c2c6cf441174550510611/.github/workflows/app-deploy.yaml#L22-L26

아, 맞네. 예약어라니;;; 이런 식으로 가면 좋겠네요.

2022-05-03 09:12 UTC, KIMTHE commented on .github/workflows/continuous-deployment.yaml
> +      TOKEN:
수정완료했습니다!

2022-05-03 09:13 UTC, KIMTHE commented on .github/workflows/continuous-deployment.yaml
> +        default: '{"include":[{"src-path":"Sms","fncapp-name":"sms"},{"src-path":"Sms.Verification","fncapp-name":"sms-verify"}]}'
```
- '[{"src-path":"Sms","fncapp-name":"sms"},{"src-path":"Sms.Verification","fncapp-name":"sms-verify"}]'
- '{[{"src-path":"Sms","fncapp-name":"sms"},{"src-path":"Sms.Verification","fncapp-name":"sms-verify"}]}'
```

다음 두가지로 테스트를 해봤는데, 에러가 뜹니다.

2022-05-04 11:37 UTC, KIMTHE commented
- continuous-deployment.yaml 을 github, azure로 분리
- 기타 변수 리팩토링
- 함수앱들의 이름을 bash shell script로 입력받아서, workflow_call inputs으로 입력

커밋완료했습니다!

2022-05-08 08:23 UTC, justinyoo requested changes
코멘트 남겨 뒀습니다!

2022-05-08 08:23 UTC, justinyoo commented on .github/workflows/continuous-integration.yaml
> +        default: '["sms","sms-verify"]'
이 부분도 마찬가지로 `required: true`로 두고 디폴트 값을 주지 않는 것이 좋겠습니다.

2022-05-08 08:23 UTC, justinyoo commented on .github/workflows/release-azure.yaml
> +        echo "::set-output name=fncapp_json::$JSON"
이 `make_fncapp_json` 이라는 job 도 `workflow_call` 로 빼면 굳이 `release-github.yaml` 파일에 중복으로 하지 않아도 될 것 같아요. 이것도 한 번 보실래요?

2022-05-08 12:56 UTC, KIMTHE commented on .github/workflows/continuous-integration.yaml
> +        default: '["sms","sms-verify"]'
pull-request.yaml의 경우에는 CI에서 matrix_json을 사용하지않는데 true로 해도 될까요?

2022-05-08 17:16 UTC, KIMTHE commented on .github/workflows/release-azure.yaml
> +        echo "::set-output name=fncapp_json::$JSON"
넵 모듈화 완료했습니다. 
사용자는 make_fncapp_json 파일에 function app 이름들을 입력하게 될 것 같습니다.

2022-05-09 05:39 UTC, justinyoo requested changes
너무 복잡하게 생각하는 것 같은데, 그렇게 복잡하게 생각하지 않으셔도 됩니다. 우리 목적은

1. 코드 푸시가 들어오면 빌드/테스트 하고 애저로 배포한다.
2. 코드 PR 들어오면 빌드/테스트한다.
3. 태그 푸시가 들어오면 빌드/테스트 하고 깃헙으로 릴리즈한다.

요 세가지인데, 어떻게 하면 최대한 간단하게 이걸 이끌어낼 수 있는지를 고민해 보세요. 지금 너무 복잡해지는 것 같음. 생각보다 의외로 간단할텐데?

2022-05-09 05:39 UTC, justinyoo commented on .github/workflows/continuous-integration.yaml
> +  Upload-App:
앞서 빌드/테스트 하는 job과 아티팩트를 만들어서 업로드 하는 이 앱의 코드베이스가 다를 수 있습니다. 따라서, 이 두 job 이 별개로 있으면 안되고 하나가 되어야 해요.

2022-05-09 05:39 UTC, justinyoo commented on .github/workflows/continuous-integration.yaml
> +        default: '["sms","sms-verify"]'
PR에서는 빌드/테스트 까지만이잖아요? 그런데 지금 이 continuous-integration.yaml 파일은 빌드/테스트/업로드 를 다 하려고 하니 문제가 생기는 것 같네요.

* PR시 빌드/테스트
* 릴리즈시 빌드/테스트/업로드

요렇게가 한 job 에서 돌아가야 합니다.

2022-05-09 05:39 UTC, justinyoo commented on .github/workflows/input-function-apps-json.yaml
> +        array_app_name=("sms" "sms-verify")
여기가 자꾸 하드코딩이 되는데... 이 값을 코드 변경 없이 할 수 있는 걸 우린 이미 알고 있죠. 깃헙 시크릿. 거기서 넘겨주는 값을 가지고 처리하는게 좋습니다.

예를 들어서...
* 깃헙 시크릿을 `AZURE_APP_SUFFIXES` 라고 하고,
* 그 값을 `sms sms-verify` 같은 식으로 넣어준다고 하면,

이 시크릿 값을 여기서 배열로 변환시키는 작업을 하는 것이 제일 좋지 않을까요? 그렇게 하면, 이 워크플로우는 변경하지 않아도, 향후 저 시크릿 값이 막 `sms sms-verify mms sos` 등등 막 추가되고 해도 아무 문제 없을 듯?

2022-05-09 05:39 UTC, justinyoo commented on .github/workflows/continuous-deployment-github.yaml
> +        asset_content_type: application/gzip
너무 복잡하게 생각하는 것 같음.

여기 두 `Pre-Work` 이랑 `Continuous-Deployment-GitHub` 이랑 하나로 합칠 수 있을 것 같은데요? 어차피 CI 쪽에서 아티팩트가 `sms`, `sms-verify` 이렇게 두 개 올라오면, 여기선 그 두 개를 그냥 다 업로드하면 되잖아요.

`matrix_json` 값으로 받아오는 JSON 개체를 활용해서 파일 이름만 버저닝하고 바로 올려도 될 것 같음. 이게 bash 스크립트로 힘들 것 같으면 파워셸 쓰셔도 됩니다.

2022-05-10 07:47 UTC, KIMTHE commented on .github/workflows/continuous-deployment-github.yaml
> +        asset_content_type: application/gzip
matrix를 사용하지않고,  shell script로 루프를 이용해서 github release에 배포하는 방식으로 구현하는건가요?

2022-05-10 07:55 UTC, KIMTHE commented on .github/workflows/continuous-integration.yaml
> +        default: '["sms","sms-verify"]'
넵 하나의 job으로 만들었습니다. 그러면 pull-request.yaml 에서도 matrix_json를 empty값으로 넣어줘야할까요?

2022-05-10 13:19 UTC, KIMTHE commented
- `continuous-integration.yaml` 를 pull-request, release 용으로 분할
- `continuous-deployment-github.yaml` 에서 matrix대신 shell script에서 loop를 이용하여, 단일 job으로 만듬
- `input-function-apps-json.yaml` 에서 function app 이름을 secrets으로 받음

커밋완료했습니다!

2022-05-10 14:27 UTC, justinyoo approved these changes
고생하셨습니다!

2022-05-10 14:30 UTC, merged