Refactoring
devrel-kr/nhn-toast-notification-service-custom-connector pull request #28
Opened 2022-05-01 15:40 UTC by dunblx05

Resolve conflict and modify function code

2022-05-01 22:30 UTC, justinyoo requested changes
코멘트 남겨뒀습니다. 확인해 보세요

2022-05-01 22:30 UTC, justinyoo commented on src/NhnToast.Sms/Models/ListMessagesOptions.cs
> +namespace Toast.Sms.Models {
중괄호 줄바꿈합니다. 닷넷 코딩 컨벤션은 중괄호를 새로운 줄에 쓰는 거예요.

2022-05-01 22:30 UTC, justinyoo commented on src/NhnToast.Sms/Triggers/SendMessages.cs
> +using Toast.Common.Configurations;
25번 라인은 중복입니다.

2022-05-01 22:30 UTC, justinyoo commented on src/NhnToast.Sms/Triggers/SendMessages.cs
> +using Toast.Sms.Configurations;
26번 라인도 중복이네요

2022-05-01 22:30 UTC, justinyoo commented on src/NhnToast.Sms/Triggers/SendMessages.cs
>              var options = new
여기 options 개체를 우리 바꿔야 하겠죠?

2022-05-01 22:31 UTC, justinyoo commented
질문: 브랜치를 어떻게 따면 저 수많은 커밋 히스토리들이 다 딸려오나요? 저 히스토리들은 계속해서 늘어나던데...?

2022-05-02 04:35 UTC, dunblx05 commented on src/NhnToast.Sms/Triggers/SendMessages.cs
>              var options = new
SendMessages 펑션은 SendMessagesOptions 모델을 만들지 않아서 그대로 두었습니다.

2022-05-02 04:36 UTC, dunblx05 commented
> 질문: 브랜치를 어떻게 따면 저 수많은 커밋 히스토리들이 다 딸려오나요? 저 히스토리들은 계속해서 늘어나던데...?

- 아마 제 생각으로는 main에서 작업을 모두 완료하고 난 후에 브랜치를 파서 커밋을 하여 생기는 문제 같습니다

- 다음에 커밋할 때 먼저 브랜치를 판 후에 작업하여 커밋을 해 보면 딸려오지 않을 것 같습니다.

2022-05-03 02:41 UTC, justinyoo commented on src/NhnToast.Sms/Triggers/SendMessages.cs
>              var options = new
필요하다면 만들어야 하지 않을까효?

2022-05-03 02:43 UTC, justinyoo requested changes
코멘트 남겨뒀습니다

2022-05-03 02:43 UTC, justinyoo commented on src/NhnToast.Sms/Triggers/SendMessages.cs
>              var options = new
아니네, 그냥 `RequestUrlOptions` 쓰면 되는 거 아닌가요?

2022-05-03 08:24 UTC, justinyoo approved these changes
좋습니다!

2022-05-03 08:24 UTC, merged