Add response-entity about ListMessage, SendMessage API
devrel-kr/nhn-toast-notification-service-custom-connector pull request #47
Opened 2022-05-12 12:43 UTC by KIMTHE

- #45 
- api문서를 참고하여 header, body에 대한 model파일 추가

2022-05-14 12:32 UTC, KIMTHE commented
커밋 완료하였습니다!

2022-05-17 06:39 UTC, justinyoo requested changes
테스트 코드는 어디에 있나요? 이거 테스트 돌려보면 원하는 결과 안 나올 것 같은데...?

2022-05-17 06:39 UTC, justinyoo commented on src/nt-common/Models/ResponseModel.cs
> +        public virtual ResponseHeaderModel header { get; set; }
C# 컨벤션상 속성은 PascalCasing 입니다. 즉, `header`가 아니라 `Header`가 되어야 해요.

2022-05-17 06:39 UTC, justinyoo commented on src/nt-common/Models/ResponseModel.cs
> +        public virtual T body { get; set; }
마찬가지로, C# 컨벤션상 속성은 PascalCasing 입니다. 즉, `body`가 아니라 `Body`가 되어야 해요.

2022-05-17 06:39 UTC, justinyoo commented on src/nt-common/Models/ResponseHeaderModel.cs
> +        public virtual string resultMessage { get; set; }
여기도 모두 PascalCasing

2022-05-17 06:42 UTC, justinyoo commented
여기 참조해 보세요: https://github.com/aliencube/nhn-toast-notification-service-custom-connector/tree/main/src/NhnToast.Sms.Verification/Models

2022-05-17 10:01 UTC, KIMTHE commented on src/nt-common/Models/ResponseModel.cs
> +        public virtual ResponseHeaderModel header { get; set; }
PascalCasing 전부 적용완료했습니다!

2022-05-17 14:30 UTC, justinyoo requested changes
불필요한 클라스 추가는 안해도 될 것 같습니다.

2022-05-17 14:30 UTC, justinyoo commented on src/nt-sms/Models/ListMessagesResponse.cs
> +
요 클라스는 불필요한 중복처럼 보여요.

2022-05-17 14:30 UTC, justinyoo commented on src/nt-sms/Models/ListMessagesResponse.cs
> +    public class ListMessagesResponse : ResponseModel<ListMessagesResponseBody> { }
지금 정의 보다는 아래처럼 바꾸는 게 간결해 보입니다.

```csharp
public class ListMessagesResponse : ResponseModel<ResponseCollectionBodyModel<ListMessagesResponseData>>
{
}
```

2022-05-17 14:30 UTC, justinyoo commented on src/nt-sms/Models/SendMessagesResponse.cs
> +    public class SendMessagesResponseBody: ResponseItemBodyModel<SendMessagesResponseData>{ }
요것도 지우는 게 낫지 싶습니다.

2022-05-17 14:30 UTC, justinyoo commented on src/nt-sms/Models/SendMessagesResponse.cs
> +    public class SendMessagesResponse : ResponseModel<SendMessagesResponseBody>{ }
대신 여기를 아래처럼 바꾸는 게 좋아 보여요.

```csharp
public class SendMessagesResponse : ResponseModel<ResponseItemBodyModel<SendMessagesResponseData>>
{
}
```

2022-05-20 16:27 UTC, KIMTHE commented
unit-test 커밋완료했습니다!

2022-05-20 16:27 UTC, KIMTHE commented on src/nt-sms/Models/ListMessagesResponse.cs
> +
불필요한 클래스 삭제 모두 완료했습니다!

2022-05-23 11:54 UTC, justinyoo approved these changes
수고하셨습니다!

2022-05-23 11:54 UTC, merged