Add RequestUrlBuilder & Unit Test
devrel-kr/nhn-toast-notification-service-custom-connector pull request #48
Opened 2022-05-13 06:37 UTC by dltmddn

RequestUrlBuilder 구현 및 단위 테스트 추가했습니다.

options를 사용하지 않고 URL을 만드는 과정에서 Endpoint의 이름과 RequestQuries 멤버의 이름을 일치하기 위해 JSONProperty를 추가했습니다.
paths는 빌더를 호출하는 task에서 이름과 값을 string[] 형태로 넘겨주는 형식으로 구현했습니다.

단위 테스트 부분이 DataRow에 quries나 header를 넘겨주지 못해서 string으로 처리하다 보니 억지로 끼워 맞춘거 같은데 개선 할 수 있는 방법이 있으까요?

2022-05-17 06:29 UTC, justinyoo requested changes
코멘트 남겨 뒀구요, 우선 두영님이랑 같이 validator 작업을 먼저 끝내시는 게 낫겠습니다.

2022-05-17 06:29 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +                var serialised = JsonConvert.SerializeObject(queries);
여기서 직렬화 할 때 `JsonSerializerSettings` 를 추가해 주지 않으면 아마도 그 다음라인에서 비직렬화 할 때 API 명세대로 camel casing 되지 않을 거예요.

이 `RequestUrlBuilder` 클라스 안에서 `JsonSerializerSettings` 인스턴스를 생성하는 대신 이걸 어디서 받아오는 형식으로 구현해 보세요. `ToastSettings` 쪽에서 받아오는 것 추천

2022-05-17 06:29 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +        }
이 로직의 의도를 잘 모르겠습니다.

2022-05-17 06:29 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            }
여기 로직이 생각보다 간단해요.

```csharp
var queries = string.Join("&", Queries.Select(p => $"{p.Key}={p.Value}"));
```

비슷하게 하면 됩니다.

우린 `local.settings.json` 파일에 있는 엔드포인트에서 ? 뒷쪽에 있는 쿼리스트링 부분을 다 걷어낼 예정이라고 말씀드렸기 때문에, 그쪽 부분이 없다 생각하고 그냥 여기서 만든 쿼리 스트링을 붙여넣는다 생각하세욥.

2022-05-17 06:29 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            }
이 부분도 마찬가지긴 한데, 만약 `string[] paths` 형태로 받아오는 게 문제가 있다고 생각하시면 이것도 query 파라미터나 header 파라미터 받아오는 식으로 강타입으로 변환해서 처리해도 될 거예요.

2022-05-17 06:29 UTC, justinyoo commented on src/nt-sms/Models/ListMessageStatusRequestQuries.cs
> +        [JsonProperty("startUpdateDate")]
앞서 언급한 바와 같이 `JsonSerializerSettings` 개체를 사용하면 필요가 없습니다.

2022-05-17 06:29 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +                .WithPaths(paths).Build();
따라서, 앞서 말씀드린 바와 같이 여기서 `WithPaths` 메소드를 좀 더 고민해 보세욥. 다른 부분은 크게 건드릴 필요가 없습니다.

2022-05-22 09:13 UTC, dltmddn commented
지난 미팅 피드백 내용 반영해서 커밋 완료 했습니다.
현재 NhnToast.Sms.Tests trigger에서 `((bool)payload.header.isSuccessful).Should().Be(expected);`에서 예외가 발생합니다.
자료형 변환 문제로 메시지가 나오는데 원인을 정확하게 파악하지 못했습니다.
다음 미팅 때 해당 부분에 대해 확인 해 주시면 감사하겠습니다.

2022-05-22 12:34 UTC, dltmddn commented
추가 수정사항 반영해서 커밋 완료 했습니다.

2022-05-25 17:48 UTC, dltmddn commented
지난번 피드백 내용 반영해서 RequestUrlBuilder 수정했습니다.
* RequestUrlBuilderTest에서 WithQueries(), WithPaths()에 정해진 BaseQueries, BasePaths가 아닌 값이 들어갈 경우 예외처리를 
Exceptions - Validator를 따로 만들어서 처리해야 하나요?
* Build()를 테스트 할 때 지금처럼 결과가 string 형태인지만 확인하면 되는 건가요?

2022-05-26 08:02 UTC, justinyoo requested changes
코멘트 남겨뒀습니다. 코멘트가 무슨 말인지 모르겠으면 디스코드에서 물어보세요. 계속 무슨 말인지 모르겠는데 자꾸 들고 있어봤자 시간만 지납니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +        private ToastSettings _settings { get; set; }
프라이빗 필드일 경우에는 `private ToastSettings _settings;` 하면 끝입니다. 주석도 필요 없고 `{ get; set; }` 도 필요 없어요.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +        private string _appKey { get; set; }
이 필드가 필요가 있나요? `_baseUrl`, `_version` 같은 경우는 굳이 선언하기 보다는 그냥 나중에 `this._settings.BaseUrl`, `this._settings.Version` 으로 써도 될 것 같은데요?

마찬가지로 `this._headers.AppKey` 같은 식으로 불러서 쓰는 게 낫습니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            }
앞서 언급한 바와 같이 굳이 `_baseUrl` 등을 선언하지 않는다면, 불필요합니다.

```csharp
this._settings = settings;
this._endpoint = endpoint;
```

정도면 충분해요.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            if (headers != null) _appKey = headers.AppKey;
마찬가지로 여기서도 `this._headers = headers;` 면 충분합니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            if (deserialised != null && deserialised.Count() != 0) _queries = String.Join("&", deserialised.Select(x => $"{x.Key}={x.Value}"));
1. 92번 라인에서 비직렬화를 한 결과가 `null` 값을 반환하는지 아니면 비어있는 딕셔너리를 반환하는지 확인해 보세요. 비직렬화 결과가 `null` 이 아니라면 굳이 `deserialised != null` 이라는 검사식을 넣을 필요가 없습니다.
2. `deserialised.Any()`를 쓰는 것이 좋습니다.
3. C# 코딩 컨벤션에서는 `if { ... }` 문을 항상 줄바꿈합니다.

```csharp
if (조건)
{
    // Do something
}
else
{
    // Do another
}
```

4. `_queries` 는 프라이빗 필드이므로 앞에 항상 `this.`를 붙입니다.
5. `String.Join(...)` 대신 `string.Join(...)`을 쓰세요.
6. 마지막으로 `deserialised` 값이 항상 `null` 이 아니라면, 굳이 이 `if` 문 자체가 필요 없습니다. 그냥 `this._queries = string.Join(...)` 해도 결과는 같아요.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            var serialised = JsonConvert.SerializeObject(paths, _settings?.SerializerSetting);
여기도 위와 마찬가지로 `this._settings` 필드가 `null`인지 아닌지 확인하는 로직이 필요합니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            if (deserialised != null && deserialised.Count() != 0) _paths = deserialised;
위의 `WithQueries(...)`와 마찬가지로 `deserialised` 값이 `null` 이 아니라면 그냥 `this._paths = deserialised;`만 해도 무방합니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            if (_baseUrl == null || _endpoint == null) return $"{_baseUrl?.TrimEnd('/')}/{_endpoint?.TrimStart('/')}";
로직이 맞지 않습니다. `this._settings`, `this._endpoint` 둘 중 하나라도 `null`이라면 에러를 뱉어야겠죠.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            _endpoint = _endpoint.Replace("{appKey}", _appKey);
`this.` 붙일 것

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +                }
1. 여기서 만약 `for ... loop`를 썼다면 `i`가 맞겠지만, 여기서는 `foreach ... loop`를 썼으므로 ``var i` 대신 `var key` 라고 하는 것이 좀 더 명확할 겁니다.
2. `this.` 붙이기

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            _endpoint = _endpoint.TrimEnd('?');
tenary operator 를 사용해서 `this._endpoint = string.IsNullOrWhiteSpace(this._queries) ? ... : ...;` 형태로 작업하시는 것이 좋습니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            return $"{_baseUrl.TrimEnd('/')}/{_endpoint.TrimStart('/')}";
가만 보니까... `this._endpoint` 값이 이 메소드에서 오염되네요? 이 메소드 내부적으로 `var requestUri` 값을 선언하고 그걸 작업하는 거 추천.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-common/Configurations/ToastSettings.cs
> +        public JsonSerializerSettings SerializerSetting = new JsonSerializerSettings() { NullValueHandling = NullValueHandling.Ignore, ContractResolver = new CamelCasePropertyNamesContractResolver()
`JsonSerializerSettings` 초기화 할 때, 한의 속성 값이 하나일 경우라면 한줄에 써도 좋지만, 지금과 같이 여러개일 경우에는 여러줄로 나눠 쓰는 것이 좋습니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +                .WithSettings<ToastSettings>(this._settings, this._settings.Endpoints.GetMessage)
`.WithSettings<ToastSettings>(...)` 대신 `.WithSettings(...)` 해도 될 거예요.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +                .WithHeaders(headers).WithQueries(queries)
여기는 굳이 `.WithHeaders(...).WithQueries(...)` 하는 대신, 두 줄로 나눠도 됩니다. 일관성.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-sms/Triggers/ListMessages.cs
> +                .WithSettings(this._settings, this._settings.Endpoints.ListMessageStatus)
엔드포인트 틀렸습니다.

2022-05-26 08:02 UTC, justinyoo commented on src/nt-sms/Triggers/SendMessages.cs
73번 라인에서 `payload` 를 만들었는데 이게 아직까지 남아있을 이유는 없죠. 지우세요. 그리고 `payloads` 아니고 `payload` 입니다.

2022-05-26 08:02 UTC, justinyoo commented on test/NhnToast.Common.Tests/Fakes/FakeRequestPaths.cs
> +    }
이거 테스트에 쓰이나요? 쓸려고 만들었으면 테스트에 쓰시고, 안 쓰면 없애세요. 왠지 쓰려고 만든 것 같은데, 테스트 메소드가 없으면, 테스트를 다 만든게 아닌 듯?

2022-05-26 08:02 UTC, justinyoo commented on test/NhnToast.Common.Tests/Fakes/FakeRequestQueries.cs
> +    }
이거 테스트에 쓰이나요? 쓸려고 만들었으면 테스트에 쓰시고, 안 쓰면 없애세요. 왠지 쓰려고 만든 것 같은데, 테스트 메소드가 없으면, 테스트를 다 만든게 아닌 듯?

2022-05-26 08:06 UTC, justinyoo commented
> 지난번 피드백 내용 반영해서 RequestUrlBuilder 수정했습니다.
> 
> * RequestUrlBuilderTest에서 WithQueries(), WithPaths()에 정해진 BaseQueries, BasePaths가 아닌 값이 들어갈 경우 예외처리를
>   RequestHeder처럼 Exceptions - Validator를 따로 만들어서 처리해야 하나요?
>   (try catch가 비용이 많이 든다고 하셔서 다른 방법이 있는지 궁금합니다.)

이미 우리가 `where T: BaseRequestQueries`, `where T: BaseRequestPaths` 라고 제약을 걸어뒀기 때문에 이상한게 들어가는 순간 에러가 나게 되어 있습니다. 굳이 유효성 검사 안하셔도 대요. 앞서 언급한 `FakeRequestQueries2`, `FakeRequestPaths2`가 이와 관련한 거라면 어차피 못 쓰는 거니 삭제하세욥.

> * Build()를 테스트 할 때 지금처럼 결과가 string 형태인지만 확인하면 되는 건가요?

`Build()` 명령어를 통해 만들어진 request URL 값이 내가 원하는 모양인지를 확인해야겠죠?

2022-05-26 11:07 UTC, dltmddn commented on src/nt-sms/Triggers/SendMessages.cs
제가 작성한 코드가 아니라 정확한 의도는 모르겠으나 밑에 결과를 받기 위한 payload와 겹쳐서 그런 것 같은데 결과를 받는 payload를 resultPayload로 고쳐서 올리겠습니다.

2022-05-26 13:09 UTC, dltmddn commented
RequestUrlBuilderTests에서 궁금한 점
1. RequestUrlBuilder에 있는 필드의 값들의 타입을 확인할 때 `SingleOrDefault(...).Should().NotBeNull().And.Subject`를 이용해서 존재 여부랑 타입까지 확인하고 싶은데 Property와는 다르게 Subject에서 FieldType이 없습니다.
확인 할 수 있는 다른 방법이 있을까요?(현재 코드는 Field가 있든 없든 다 맞다고 나옵니다... 하하....)
2. `WithQueries( )`랑 `WithPaths( )`를 확인할 때 지금처럼 default 형태로 parameter를 넣어준 뒤 예상되는 결과를 비교하는 방식이 맞나요?
3. `build( )`를 확인할 때 paths와 queries가 비어있는 추상 클래스를 받으니까 해당 부분은 다 없어지고 지금과 같은 상태가 최종 URL이 맞나요?

2022-05-29 09:08 UTC, justinyoo commented
> RequestUrlBuilderTests에서 궁금한 점
> 
> 1. RequestUrlBuilder에 있는 필드의 값들의 타입을 확인할 때 `SingleOrDefault(...).Should().NotBeNull().And.Subject`를 이용해서 존재 여부랑 타입까지 확인하고 싶은데 Property와는 다르게 Subject에서 FieldType이 없습니다.

그 앞에서 PropertyInfo 타입으로 받아오면 Subject 가 FieldType 아 아닐 거예요. FieldInfo 타입으로 받아와야 Subject에 FieldType이 보일 거예요.


>    확인 할 수 있는 다른 방법이 있을까요?(현재 코드는 Field가 있든 없든 다 맞다고 나옵니다... 하하....)

이렇게 되면 테스트 결과값이 false positive 가 됩니다. 가장 조심해야 하는 부분입니다.

> 2. `WithQueries( )`랑 `WithPaths( )`를 확인할 때 지금처럼 Fake 클래스 인스턴스를 넣어준 뒤 예상되는 결과를 비교하는 방식이 맞나요?

우리는 Fake 클라스를 통해 Base 클라스를 테스트합니다.

> 3. `build( )`를 테스트 할 때 paths와 queries가 Fake 클래스를 받으니까 query와 path는 다 없어지고 baseurl에 endpoint만 붙은 형식으로 테스트 하는게 맞나요?

Fake 클라스를 통해서 우리가 테스트 하는 대상이 무엇인지를 먼저 고민해 보세요.

2022-05-29 09:08 UTC, justinyoo requested changes
코멘트 남겨뒀습니다.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            }
아래 `WithQueries`, `WithPaths`, `Build` 등의 메소드에서 this._settings 값이 있는지 없는지 확인하는 절차가 있기 때문에 여기서는 그냥 무지성으로 할당하면 됩니다. 굳이 `if { ... }` 문이 필요 없어요.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            }
만약 `this._settings` 값이 `null` 이라면 아예 쿼리스트링 값을 변환하지 않는 것이 아니라, 예외를 던져야죠.

`if (this._settings == null) throw new InvalidOperationException(...);` 같은 형식이 되어야 합니다. 물론 줄바꿈은 하세욥.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            }
마찬가지로 만약 `this._settings` 값이 `null` 이라면 아예 Path 값을 변환하지 않는 것이 아니라, 예외를 던져야죠.

`if (this._settings == null) throw new InvalidOperationException(...);` 같은 형식이 되어야 합니다. 물론 줄바꿈은 하세욥.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            requestUrl = (string.IsNullOrWhiteSpace(this._queries)) ? requestUrl : $"{requestUrl}?{this._queries}";
이 로직 대로라면 터너리 오퍼레이터 대신 `if (!string.IsNullOrWhiteSpace(this._queries)) { requestUrl += $"?{this._queries}"; }` 같은 식이면 충분할 것 같은데요? 물론 줄바꿈 하셔야 합니다.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-common/Builders/RequestUrlBuilder.cs
> +            if (_paths != null)
`this._paths` 입니다.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-sms/Triggers/SendMessages.cs
> +            var content = new ObjectContent<object>(payload, new JsonMediaTypeFormatter(), "application/json");
* payload 타입이 `object` 가 아니라 다른 거죠? 확인해 보고 수정해 주세욥.
* 혹시 `JsonMediaTypeFormatter`가 꼭 필요한가요? 굳이 필요하지 않으면 없애도 되구요, 필요하다면 이걸 ToastSettings 쪽에서 JsonSerializerSettings 와 함께 묶어서 의존성 주입을 할 수 있으니 확인해 보세요.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-sms/Triggers/SendMessages.cs
>              // Act
`// Act` 는 테스트 할 때나 쓰는 거니까 빼십쇼.

2022-05-29 09:08 UTC, justinyoo commented on src/nt-sms/Triggers/SendMessages.cs
> +            var resultPayload = await result.Content.ReadAsAsync<object>().ConfigureAwait(false);
`<object>` 대신 우리 새롭게 정의한 응답 개체 있죠? 그걸로 바꾸세요.

2022-05-30 11:59 UTC, justinyoo approved these changes

2022-05-30 11:59 UTC, merged