Add response-entity aboutGetMessage, ListMessageStatus API
devrel-kr/nhn-toast-notification-service-custom-connector pull request #49
Opened 2022-05-14 12:37 UTC by wlals761

- GetMessage, ListMessageStatus API에 대한 응답개체를 작성하였습니다.
- header, body에 대한 모델은 민수꺼에 있습니다.
- 바디모델에 공통되는 부분은 common에 ResponseBodyModel, ResponseBodyListModel을 추가하였습니다.(민수꺼와 동일)

2022-05-22 01:55 UTC, wlals761 commented
커밋 완료하였습니다!

2022-05-26 08:12 UTC, justinyoo requested changes
코멘트 남겨뒀습니다!

2022-05-26 08:12 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Models/GetMessageResponseModelTest.cs
> +            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
1. 우리가 보는 request/response payload 에서 `xxx = null`로 표시해야 하는 경우가 있다면 첫번째 주석처리한 건 맞구요,
2. 두번째랑 세번째 `Formatting`, `ReferenceLoopHandling` 항목이 필요한가요? 없어도 될 것 같은데...?

2022-05-26 08:12 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Models/GetMessageResponseModelTest.cs
> +        [DataRow("20180810100630ReZQ6KZzAH0", "2018-08-10 10:06:30.0", "2018-08-10 10:06:42.0", "TemplateId", "템플릿명", 0, "카테고리명", "본문", "15446859", "82", "01000000000", "3", "성공", "1000", " 성공", 1000
여기서는 굳이 한글로 된 테스트 데이터가 필요없으니 수정해 주세욥.

2022-05-26 08:12 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Models/ListMessageStatusResponseModelTest.cs
> +            ReferenceLoopHandling = ReferenceLoopHandling.Ignore,
1. 우리가 보는 request/response payload 에서 `xxx = null`로 표시해야 하는 경우가 있다면 첫번째 주석처리한 건 맞구요,
2. 두번째랑 세번째 `Formatting`, `ReferenceLoopHandling` 항목이 필요한가요? 없어도 될 것 같은데...?

2022-05-26 08:12 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Models/ListMessageStatusResponseModelTest.cs
> +        [DataRow("sms", "lorem ipsum", 0, "1000", "성공", "2018-10-04 16:16:00.0", "2018 - 10 - 04 16:17:10.0", "2018-10-04 16:17:15.0", "10003", "LGU", "senderGroupingKey", "recipientGroupingKey")]
여기서는 굳이 한글로 된 테스트 데이터가 필요없으니 수정해 주세욥.

2022-05-26 09:57 UTC, wlals761 commented
수정 사항들 수정하였고 body에 대한 open-api example 클래스(ListMessageStatusResponseModelExample, GetMessageResponseModelExample)도 추가하였습니다!

2022-05-29 12:16 UTC, justinyoo requested changes
코멘트 남겨뒀습니다

2022-05-29 12:16 UTC, justinyoo commented on src/nt-sms/Models/GetMessageResponse.cs
> +    public class GetMessageResponseBody : ResponseItemBodyModel<GetMessageResponseData> { }
이 클라스는 위의 `GetMessageResponse` 클라스와 차이가 없습니다. 빼도 무방함.

2022-05-29 12:16 UTC, justinyoo commented on src/nt-sms/Models/GetMessageResponse.cs
> +                Body = new GetMessageResponseBody()
`GetMessageResponse` 로 바꿔도 됩니다.

2022-05-29 12:16 UTC, justinyoo commented on src/nt-sms/Models/ListMessageStatusResponse.cs
> +    public class ListMessageStatusResponseBody : ResponseCollectionBodyModel<ListMessageStatusResponseData> { }
마찬가지로 얘도 필요 없을 듯?

2022-05-30 12:00 UTC, merged