Add open-api body examples about ListMessages, SendMessages endpoints
devrel-kr/nhn-toast-notification-service-custom-connector pull request #55
Opened 2022-05-24 18:14 UTC by KIMTHE

- [api문서](https://github.com/Azure/azure-functions-openapi-extension/blob/main/docs/openapi-core.md#openapiresponsewithbodyattribute)를 참고하여 body에 대한 open-api example 클래스 추가
    - `ListMessagesResponseModelExample`
    - `SendMessagesResponseModelExample, SendMessagesRequestBodyModelExample`

2022-05-25 07:31 UTC, KIMTHE commented
커밋완료했습니다!

- response body example 캡처입니다.
![image](https://user-images.githubusercontent.com/29460783/170205379-de0550a8-f24a-4f69-a468-f77e488e826c.png)

- request body example 캡처입니다.
    - 코드에는 예시값들을 할당했으나, swagger ui에는 response와는 달리 type이 할당되어 있습니다.
![image](https://user-images.githubusercontent.com/29460783/170205560-e983ddbe-8203-4090-b100-d92901c7b21c.png)


- 객체 생성을 위해, 삭제했던 `ListMessagesResponseBody, SendMessagesResponseBody` 을 다시 만들었습니다.

2022-05-26 08:15 UTC, justinyoo requested changes
코멘트 남겨뒀습니다.

2022-05-26 08:15 UTC, justinyoo commented on src/nt-sms/Models/ListMessagesResponse.cs
> +                                    CarrierName = "SKT",
혹시 여기 나오는 값이 실제로 한글로 나오든가요? 만약 그렇지 않다면 굳이 한글로 하실 필요는 없어요. 그리고, 보내는 사람, 받는 사람 전화번호 같은 건 실제로 있을법한 번호 쓰시면 나중에 문제가 될 수 있어요.

2022-05-26 08:29 UTC, KIMTHE commented on src/nt-sms/Models/ListMessagesResponse.cs
> +                                    CarrierName = "SKT",
넵 한글로 나오지 않는 것은 수정했습니다. 유의사항 수정완료했습니다!

2022-05-29 12:19 UTC, justinyoo requested changes
코멘트 남겨뒀습니다!

2022-05-29 12:19 UTC, justinyoo commented on src/nt-sms/Models/ListMessagesResponse.cs
> +    public class ListMessagesResponseBody : ResponseCollectionBodyModel<ListMessagesResponseData> { }
이게 굳이 필요 없을 듯 싶어요. 만약 ResponseCollectionBodyModel 클라스가 abstract 라면 그걸 풀면 될 듯

2022-05-29 12:19 UTC, justinyoo commented on src/nt-sms/Models/SendMessagesResponse.cs
> +    public class SendMessagesResponseBody : ResponseItemBodyModel<SendMessagesResponseData> { }
이게 굳이 필요 없을 듯 싶어요. 만약 ResponseItemBodyModel 클라스가 abstract 라면 그걸 풀면 될 듯

2022-05-29 12:26 UTC, KIMTHE commented on src/nt-sms/Models/ListMessagesResponse.cs
> +    public class ListMessagesResponseBody : ResponseCollectionBodyModel<ListMessagesResponseData> { }
수정완료했습니다!

2022-05-29 12:26 UTC, KIMTHE commented on src/nt-sms/Models/SendMessagesResponse.cs
> +    public class SendMessagesResponseBody : ResponseItemBodyModel<SendMessagesResponseData> { }
수정완료했습니다!

2022-05-30 12:01 UTC, merged