Modify Regex Dependency in Validator Class
devrel-kr/nhn-toast-notification-service-custom-connector pull request #72
Opened 2022-08-25 12:56 UTC by hsh108868

관련 이슈: [Validator 클라스 안의 Regex 의존성 수정하기 #70 ](https://github.com/devrel-kr/nhn-toast-notification-service-custom-connector/issues/70)
작업 사항: nt-sms 내부 Validator 클래스에 있는 Regex 객체들을 싱글톤으로 구조 변경하여 개별 클래스와 인터페이스로 분리하고 해당 Regex 객체 바탕으로 Validator의 Regex 의존성 수정

2022-08-26 01:03 UTC, justinyoo requested changes
리뷰 남겨뒀습니다! 거의 다 잘 하셨쎄요. 조금만 더 보시면 될 것 같구요, 다만 `RegexDateTimeWrapper` 클래스 자체에 대한 테스트가 없으니 그걸 추가해 주세욥!

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
> +        public ListMessageStatusRequestQueryValidator(IRegexDateTimeWrapper iRegexDateTimeWrapper)
이건 마이너한 내용인데, 파라미터 이름을 `regex` 정도로 줄여도 상관 없습니다. 만약에 둘 이상의 regex 인스턴스가 들어온다면 그 땐 `regexDateTime` 이라든가 하는 식으로 하는게 낫겠지만요.

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
> -        }
요 메소드는 살려두시고, 이 안에서 `return this._regex.IsMatch(date);` 를 호출하면 좋습니다.

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
> +            this.RuleFor(p => p.EndUpdateDate).Must(iRegexDateTimeWrapper.IsMatch).NotEmpty().GreaterThan(q => q.StartUpdateDate);
그러면 여기는 건드릴 필요가 없겠죠?

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
>          /// <summary>
단, 여기에 `private readonly IRegexDateTimeWrapper _regex;` 를 프라이빗 필드로 정의하고, 생성자 안에서 파라미터를 이 프라이빗 필드로 할당하는 작업을 맨 처음에 추가해 놓으면 됩니다.

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +        public ListMessagesRequestQueryValidator(IRegexDateTimeWrapper iRegexDateTimeWrapper)
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +                .Must(iRegexDateTimeWrapper.IsMatch)
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +                .Must(iRegexDateTimeWrapper.IsMatch)
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +                .Must(iRegexDateTimeWrapper.IsMatch)
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +                .Must(iRegexDateTimeWrapper.IsMatch)
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +            this.RuleFor(p => p.EndResultDate).Must(iRegexDateTimeWrapper.IsMatch).GreaterThan(p => p.StartResultDate).When(p => p.EndResultDate != null);
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> -        }
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +    /// </summary>
요기 코멘트 내용은 클래스에 붙는 거니까 확인해 보시구요. 인터페이스용 코멘트는 다른 인터페이스 참조해서 다시 달아주세욥.

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +        bool IsMatch(string date);
여기에는 코멘트 붙여 주시구요. 다른 `bool` 반환하는 메소드 찾아서 확인해 보시고 비슷한 패턴으로 달아주세욥.

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +    public class RegexDateTimeWrapper : IRegexDateTimeWrapper
여기에는 클래스 코멘트 달아주시구요

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +        public bool IsMatch(string date)
여기에 붙는 코멘트는 이미 인터페이스에 달아뒀으니 `/// <inheridtoc />` 정도로만 달아두셔도 됩니다.

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/SendMessagesRequestBodyValidator.cs
> +        public SendMessagesRequestBodyValidator(IRegexDateTimeWrapper iRegexDateTimeWrapper)
앞서와 마찬가지로 해 주세요

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/SendMessagesRequestBodyValidator.cs
> +            this.RuleFor(p => p.RequestDate).Must(iRegexDateTimeWrapper.IsMatch).When(p => !string.IsNullOrWhiteSpace(p.RequestDate));
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on src/nt-sms/Validators/SendMessagesRequestBodyValidator.cs
> -        }
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
이 메소드는 `ListMessageStatusRequestQueryValidator.Validate()` 메소드를 테스트하는 테스트 메소드예요. 따라서, 우리가 인터페이스를 만든 목적에 맞게 `var wrapper = new Mock<IRegexDateTimeWrapper>();` 정도로 목킹하시고, 그 다음에서 `wrapper.Setup(p => p.IsMatch(It.IsAny<string>()).Returns(true);` 또는 `wrapper.Setup(p => p.IsMatch(It.IsAny<string>()).Returns(false);` 정도로 결과값을 "했다치고" 형태로 만들어서 테스트 하십쇼.

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessagesRequestQueryValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessagesRequestQueryValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessagesRequestQueryValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/SendMessagesRequestBodyValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/SendMessagesRequestBodyValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-26 01:03 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/SendMessagesRequestBodyValidatorTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
여기도 마찬가지

2022-08-27 02:41 UTC, justinyoo requested changes
곧 `RegexDateTimeWrapper` 클라스를 테스트하는 테스트케이스도 추가해 주신다고 알고 있겠습니다!

2022-08-27 02:41 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
> +            this._regex = regex;
`regex` 라는 인스턴스가 들어올 때 null 체크가 빠졌습니다. 다른 생성자 참조해서 null 체크 로직 추가해 주세요.

2022-08-27 02:41 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +            this._regex = regex;
여기도 널 체크

2022-08-27 02:41 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +        List<string> subResultCodeType = new List<string>() { "MTR2_1", "MTR2_2", "MTR2_3" };
요 부분은 나중에 다시 리팩토링한다고 생각해야 할 것 같아요. 지금 PR하고는 상관 없으니 나중에 다시 한 번 보시지욥.

2022-08-27 02:41 UTC, justinyoo commented on src/nt-sms/Validators/SendMessagesRequestBodyValidator.cs
> +            this._regex = regex;
여기도 널 체크

2022-08-27 02:41 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
> +            }
여기서는 굳이 `if (date == null) { ... }` 블록이 필요할까 한 번 고민해 보시면 좋겠습니다.

2022-08-27 02:41 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
>              }
여기서도 굳이 `if (date == null) { ... }` 블록이 필요할까 한 번 고민해 보시면 좋겠습니다.

2022-08-27 02:41 UTC, justinyoo commented on src/nt-sms/Validators/SendMessagesRequestBodyValidator.cs
> +            }
여기서도 굳이 `if (date == null) { ... }` 블록이 필요할까 한 번 고민해 보시면 좋겠습니다.

2022-08-27 04:38 UTC, justinyoo requested changes

2022-08-27 04:38 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/RegexDateTimeWrapperTests.cs
> +            IRegexDateTimeWrapper iRegexDateTimeWrapper = new RegexDateTimeWrapper();
C#의 컨벤션은 정말로 필요하지 않는 이상 `var`를 사용합니다. 따라서 이 라인은 대략...

```csharp
var wrapper = new RegexDateTimeWrapper();
```

정도로 표현하면 좋습니다.

2022-08-27 04:38 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/RegexDateTimeWrapperTests.cs
> +            var result = iRegexDateTimeWrapper.IsMatch(date).Should().Be(expected);
테스트는 기본적으로 1) Arrange, 2) Act, 3) Assert 의 순서를 따라갑니다. 위의 라인에서 Arrange는 표현했으나, 이 라인에서 Act와 Assert를 한번에 구현했기 때문에 유지보수를 하려는 미래의 나에게는 코드 파악이 어려울 수 있습니다.

따라서, 이 부분은 보통 이런 식으로 표현하면 좋습니다.

```csharp
// Act
var result = wrapper.IsMatch(date);

// Assert
result.Should().Be(expected);
```

2022-08-28 11:10 UTC, justinyoo requested changes
코멘트 남겨뒀습니다. 테스트가 실패하는 경우를 보니 뭔가 목킹 값을 조정해야 할 것 같습니다.

2022-08-28 11:10 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
> +            return (date != null) ? _regex.IsMatch(date) : false ;
이미 `Regex.IsMatch(...)` 에서 date 값이 null 인지 아닌지를 체크하는데도 여기서 한 번 더 체크하는 이유가 있나요?

2022-08-28 11:10 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +            return (date != null) ? _regex.IsMatch(date) : false ;
마찬가지로, 이미 `Regex.IsMatch(...)` 에서 date 값이 null 인지 아닌지를 체크하는데도 여기서 한 번 더 체크하는 이유가 있나요?

2022-08-28 11:10 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +            return (date != null) ? _regex.IsMatch(date) : false ;
여기선 원래대로 if 블록으로 풀어 쓰는 게 가독성이 높습니다.

2022-08-28 11:10 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +        private static Regex _regex = new Regex(@"^([0-9][0-9][0-9][0-9])-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[0-1]) ([01][0-9]|2[0123]):([0-5][0-9]):([0-5][0-9])$");
정적 필드의 경우에는 private 일 경우 앞에 관례적으로 언더스코어를 붙이지 않습니다.

2022-08-28 11:10 UTC, justinyoo commented on src/nt-sms/Validators/SendMessagesRequestBodyValidator.cs
> +            return (date != null) ? _regex.IsMatch(date) : false ;
마찬가지로, 이미 `Regex.IsMatch(...)` 에서 date 값이 null 인지 아닌지를 체크하는데도 여기서 한 번 더 체크하는 이유가 있나요?

2022-08-28 11:10 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            wrapper.Setup(p => p.IsMatch(It.IsAny<string>())).Returns(false);
이 값을 `false`로 지정하면 유효성 검사를 통과하지 못했다고 가정하는 건데, 이 테스트가 그게 맞나요?

2022-08-28 11:10 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            wrapper.Setup(p => p.IsMatch(It.IsAny<string>())).Returns(true);
테스트 메소드 이름에서 이미 `It_Should_Throw_Exception`라고 언급하고 있으니, 이 테스트 메소드는 유효성 검사를 통과하지 못했다는 걸 가정하는 거니까 여기서는 `false` 값이 되어야 하지 않을까요?

2022-08-28 11:10 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessagesRequestQueryValidatorTests.cs
> +            wrapper.Setup(p => p.IsMatch(It.IsAny<string>())).Returns(true);
테스트 메소드 제목을 보시면 여기서 `true` 라고 해야 할 지, `false` 라고 해야 할 지 알 수 있을 겁니다.

2022-08-28 11:10 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/SendMessagesRequestBodyValidatorTests.cs
> +            wrapper.Setup(p => p.IsMatch(It.IsAny<string>())).Returns(true);
테스트 메소드 이름을 다시 한 번 살펴보세요

2022-08-28 11:44 UTC, MultiDCP commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +            return (date != null) ? _regex.IsMatch(date) : false ;
RegexDateTimeWrapper 클래스의 IsMatch 함수도 이름을 Regex의 IsMatch 함수와 이름을 달리하는 것이 깔끔할까요? 아니면 당장은 딱히 고치지 않아도 상관없는 부분일까요?

2022-08-28 12:39 UTC, MultiDCP commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +            return (date != null) ? _regex.IsMatch(date) : false ;
> 여기선 원래대로 if 블록으로 풀어 쓰는 게 가독성이 높습니다.

RegexDateTimeWrapper 클래스의 IsMatch 함수도 이름을 Regex의 IsMatch 함수와 이름을 달리하는 것이 깔끔할까요? 아니면 당장은 딱히 고치지 않아도 상관없는 부분일까요?

2022-08-28 15:03 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +            return (date != null) ? _regex.IsMatch(date) : false ;
이건 래퍼 클라스이기 때문에 가급적이면 원래 Regex 클래스의 메소드명을 그대로 가져가는 것이 좋습니다.

2022-08-28 15:12 UTC, justinyoo requested changes
코멘트 남겼습니다!

2022-08-28 15:12 UTC, justinyoo commented on src/nt-sms/Validators/ListMessageStatusQueryValidator.cs
> +            return _regex.IsMatch(date);
52번 라인과 마찬가지로 `_regex` 필드는  메소드 안의 로컬 변수가 아니기 때문에 컨벤션상 `this._regex`로 표현하는 것이 명확합니다.

2022-08-28 15:12 UTC, justinyoo commented on src/nt-sms/Validators/ListMessagesQueryValidator.cs
> +            return _regex.IsMatch(date);
48번 라인과 마찬가지로 _regex 필드는 메소드 안의 로컬 변수가 아니기 때문에 컨벤션상 this._regex로 표현하는 것이 명확합니다.

2022-08-28 15:12 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +            }
이미 `if { ... }` 블록 안에서 `return` 구문을 사용했으므로 여기서는 굳이 `else { ... }` 블록이 필요 없습니다. 곧바로 `return` 구문 쓰는 것이 코드 복잡도를 줄이는 방향입니다.

2022-08-28 15:12 UTC, justinyoo commented on src/nt-sms/Validators/SendMessagesRequestBodyValidator.cs
> +            return _regex.IsMatch(date);
48번 라인과 마찬가지로 _regex 필드는 메소드 안의 로컬 변수가 아니기 때문에 컨벤션상 this._regex로 표현하는 것이 명확합니다.

2022-08-28 15:12 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            wrapper.Setup(p => p.IsMatch(It.IsAny<string>())).Returns(expected);
여기서 `expected` 값은 이 `Validator.Validate(...)` 메소드의 결과값에 대한 예상치이지 이 목킹 결과값에 대한 예상치가 아니므로 이렇게 작성하면 테스트를 무조건 통과하는 의미없는 테스트 코드가 됩니다.

2022-08-28 15:12 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessagesRequestQueryValidatorTests.cs
> +            wrapper.Setup(p => p.IsMatch(It.IsAny<string>())).Returns(expected);
마찬가지로 여기서 `expected` 값은 이 `Validator.Validate(...)` 메소드의 결과값에 대한 예상치이지 이 목킹 결과값에 대한 예상치가 아니므로 이렇게 작성하면 테스트를 무조건 통과하는 의미없는 테스트 코드가 됩니다.

2022-08-28 15:12 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/SendMessagesRequestBodyValidatorTests.cs
> +            wrapper.Setup(p => p.IsMatch(It.IsAny<string>())).Returns(expected);
마찬가지로 여기서 `expected` 값은 이 `Validator.Validate(...)` 메소드의 결과값에 대한 예상치이지 이 목킹 결과값에 대한 예상치가 아니므로 이렇게 작성하면 테스트를 무조건 통과하는 의미없는 테스트 코드가 됩니다.

2022-08-30 11:02 UTC, justinyoo requested changes
거의 다 왔습니다. 조금만 힘 내 주세요!

2022-08-30 11:02 UTC, justinyoo commented on src/nt-sms/Validators/RegexDateTimeWrapper.cs
> +            if (date == null)
혹시 이것도 `date.IsNullOrWhiteSpace()` 로 바꿀 수 있을 겁니다

2022-08-30 11:02 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
>              var result = validator.Validate(queries);
이 테스트의 목적을 한 번만 더 생각해 볼까요?

이 테스트는 `ListMessageStatusRequestQueryValidator.Validate()` 메소드가 결과값을 반환하는지를 테스트 하려는 거예요. 즉 `result.IsValid` 값이 `true` 인지 `false`인지만 보려는 겁니다. 이 때 정규식이 검사하려는 부분은 날짜/시간 형식인데, 이 테스트에서는 이 검사를 "했다 치고" 넘어가는 거죠. 실제 날짜 포맷에 상관 없이 무조건 날짜/시간 형식이 맞다(`true`) 혹은 틀리다(`false`)라고 가정한 후에 다른 것들만 체크하는 거예요.

* 이 날짜/시간 형식이 틀리다(`false`)라고 가정한다면 `result.IsValid` 값은 무조건 `false`가 되겠죠?
* 이 날짜/시간 형식이 맞다(`true`)라고 가정한다면 다른 유효성 검사값들 결과에 따라 `result.IsValid` 값이 결정되겠죠?

이런 가정 아래에서 `DataRow(...)`에 정의해 놓은 값들이 맞는 지도 확인해 보셔야 합니다.

---

만약에 `Mock<IRegexDateTimeWrapper>`를 사용하지 않고 실제 인스턴스인 `RegexDateTimeWrapper`를 사용한다면 어떨까요? 이 때에는 `DataRow(...)`에 정의해 놓은 값들이 맞나요?

2022-08-31 12:17 UTC, justinyoo requested changes
아마도 마지막 리뷰 코멘트가 될 것 같습니다. 이것만 확인해 보세욥!

2022-08-31 12:17 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            var validator = new ListMessageStatusRequestQueryValidator(wrapper.Object);
그렇다면 여기도 목킹하는 대신 실제 인스턴스를 넣어 보세요

2022-08-31 12:17 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessageStatusRequestQueryValidatorTests.cs
> +            var validator = new ListMessageStatusRequestQueryValidator(wrapper.Object);
그렇다면 여기도 목킹하는 대신 실제 인스턴스를 넣어 보세요

2022-08-31 12:17 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessagesRequestQueryValidatorTests.cs
> +            var validator = new ListMessagesRequestQueryValidator(wrapper.Object);
그렇다면 여기도 목킹하는 대신 실제 인스턴스를 넣어 보세요

2022-08-31 12:17 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/ListMessagesRequestQueryValidatorTests.cs
> +            var validator = new ListMessagesRequestQueryValidator(wrapper.Object);
그렇다면 여기도 목킹하는 대신 실제 인스턴스를 넣어 보세요

2022-08-31 12:17 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/SendMessagesRequestBodyValidatorTests.cs
> +            var validator = new SendMessagesRequestBodyValidator(wrapper.Object);
그렇다면 여기도 목킹하는 대신 실제 인스턴스를 넣어 보세요

2022-08-31 12:17 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Validators/SendMessagesRequestBodyValidatorTests.cs
> +            var validator = new SendMessagesRequestBodyValidator(wrapper.Object);
그렇다면 여기도 목킹하는 대신 실제 인스턴스를 넣어 보세요

2022-08-31 13:18 UTC, justinyoo approved these changes
수고하셨습니다!

2022-08-31 13:18 UTC, merged