Endpoint Refactoring
devrel-kr/nhn-toast-notification-service-custom-connector pull request #77
Opened 2022-09-13 10:11 UTC by wnsgml7267

관련 이슈 : [엔드포인트 리팩토링 #63 ](https://github.com/devrel-kr/nhn-toast-notification-service-custom-connector/issues/63)
작업 사항 : nt-sms 내부의 Triggers 폴더에 있는 엔드포인트들의 동일한 워크플로우를 가진 메소드를 하나의 서비스 레이어를 생성하여 Fluent API 형태로 리팩토링

2022-09-13 14:41 UTC, justinyoo requested changes
일단 불필요한 파일들은 푸시하면 안됩니다!

2022-09-13 14:41 UTC, justinyoo commented on Program.cs
> +Console.WriteLine("Hello, World!");
이 파일은 필요없지 싶은데... 어디에 쓰는 물건인가요?

2022-09-13 14:41 UTC, justinyoo commented on nhn-toast-notification-service-custom-connector.csproj
> +</Project>
마찬가지로 이것도...?

2022-09-13 15:27 UTC, wnsgml7267 commented on Program.cs
> +Console.WriteLine("Hello, World!");
실수로 들어간 것 같습니다. 삭제하도록 하겠습니다..!

2022-09-13 15:28 UTC, wnsgml7267 commented on nhn-toast-notification-service-custom-connector.csproj
> +</Project>
삭제하도록 하겠습니다..!

2022-09-14 14:27 UTC, justinyoo requested changes
제 샘플 코드를 그냥 복붙한 것 까지는 괜찮은데... 그게 어떤 역할을 하는 건지는 이해하신 거죠? ㅠ

2022-09-14 14:27 UTC, justinyoo commented on src/nt-common/Models/ResponseModel.cs
> +
코드를 머지하면서 찌꺼기가 많이 남아있네요. 이 부분은 필요 없으니 지우세요.

2022-09-14 14:27 UTC, justinyoo commented on src/nt-common/Models/ResponseModel.cs
> +    public abstract class ResponseModel<T> : ResponseModel
여기에는 `///` 로 시작하는 클래스 코멘트를 붙여주세요.

2022-09-14 14:27 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +        public GetMessage(ToastSettings<SmsEndpointSettings> settings, IHttpTriggerWorkflow workflow, IValidator<GetMessageRequestQueries> validator, IHttpClientFactory factory, ILogger<GetMessage> l
`IHttpTriggerWorkflow` 인스턴스가 이미 의존성 개체로 들어갔기 때문에 더이상 `IHttpClientFactory` 인스턴스가 필요 없을 겁니다. 확인해 보세요.

2022-09-14 14:27 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +            var workflow = new HttpTriggerWorkflow(this._http);
생성자에서 `IHttpTriggerWorkflow` 인스턴스가 의존성 개체로 들어갔으니, 이건 더이상 필요 없죠?

2022-09-14 14:27 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +                                         .BuildRequestUrlAsync(this._settings.Endpoints.GetMessage, this._settings, new GetMessageRequestPaths() { RequestId = requestId })
제가 그냥 샘플 코드 형태로 넣느라 `new GetMessageRequestPaths() { RequestId = requestId }` 이렇게 추가한 건데, 이건 가독성 면에서 좀 더 고려해 보셔야 할 거예요.

2022-09-14 14:27 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
>              var headers = default(RequestHeaderModel);
74번 라인 - 104번 라인이 이제는 더이상 필요 없겠죠?

2022-09-14 16:42 UTC, wnsgml7267 commented
> 제 샘플 코드를 그냥 복붙한 것 까지는 괜찮은데... 그게 어떤 역할을 하는 건지는 이해하신 거죠? ㅠ

복붙에 관해서 팀 회의하면서도 나온 내용으로, 원래는 이해가 더 중요하다 생각하여 샘플 코드를 분석하면서 천천히 하려 했습니다. 그러나 빌드 깨지는 걸 생각 못해서 빠르게 수정하느라 아직 완벽하게 다 이해하진 못한 것 같습니다. 제가 수정하면서 어떤 부분이 변경되었는지 찾아가 보면서 했지만, 팀원 모두가 같이 해본 것도 아니라서 한 번 회의나 코드 재분석을 통해 더 제대로 이해를 해보도록 하겠습니다!

2022-09-15 01:38 UTC, wnsgml7267 commented on src/nt-sms/Triggers/GetMessage.cs
> +                                         .BuildRequestUrlAsync(this._settings.Endpoints.GetMessage, this._settings, new GetMessageRequestPaths() { RequestId = requestId })
`var paths = new GetMessageRequestPaths() {RequestId = requestId};`

이런식으로 변수에 담아서 사용하는 것은 가독성 면에서 차이가 없을까요?

2022-09-15 02:40 UTC, justinyoo requested changes
전체적으로 우선 CI 빌드 자체가 깨지진 않으니 많이 코드 품질이 좋아진 것 같구요, 기본적인 로직은 얼추 다 된 것 같긴 해요. 이제, 테스트 코드를 좀 더 고민해서 달아보세요. 제 코드를 보면 예외를 던질 때, 예외를 던지지 않을 때 등등의 케이스를 다 포함하고 있으니 코드 분석을 잘 해 보시면 좋겠습니다.

2022-09-15 02:40 UTC, justinyoo commented on src/nt-common/Models/ResponseModel.cs
> +    /// This represents the model entity for response.
4번 줄이랑 동일한데... 혹시 클라스 이름이 다르니까 (제네릭을 포함하니까) 써머리도 살짝 다르게 줄 수 있나요?

2022-09-15 02:40 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +                var payload_ = await this._workflow.ValidateHeaderAsync(req)
아래 삭제한 라인에 이미 `payload` 변수가 있어서 여기에선 어쩔 수 없이 `payload_` 변수 네이밍을 임시로 사용했습니다. 이제는 원래대로 `payload`를 사용해야 하지 않을까효?

2022-09-15 02:40 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +                                         .BuildRequestUrlAsync(this._settings.Endpoints.GetMessage, this._settings, new GetMessageRequestPaths() { RequestId = requestId })
저는 오히려 좋다고 봅니다!

2022-09-15 02:40 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +        }
이 생성자는 아마도 더이상 필요 없을 겁니다. 제가 이걸 넣었던 이유는 트리거에서 샘플로 보여준다고 넣었던 거라...

2022-09-15 02:40 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                             .Validate();
`Validate()` 메소드 뒤에 `ConfigureAwait(false)` 붙여주세욥

2022-09-15 02:40 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                request.Content = new StringContent(serialised, Encoding.UTF8, MediaTypeNames.Application.Json);
혹시 이 부분에서 저는 `StringContent` 를 사용했는데, `ObjectContent` 랑 한 번 비교해 보시고 어떤게 더 나을지 한 번 검토해 보세욥

2022-09-15 02:40 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +        /// Validates the request payload.
써머리가 틀립니다!

2022-09-15 02:40 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +        /// <typeparam name="T">Type of the request payload object.</typeparam>
여기도 써머리가 틀립니다!

2022-09-15 02:40 UTC, justinyoo commented on test/NhnToast.Sms.Tests/Workflows/HttpTriggerWorkflowTests.cs
> +}
사실 이 테스트 메소드는 HTTP POST에 대해서만 테스트한 거잖아요? 그런데, 지금 우리가 리팩토링한 것은 GetMessage 였으니... HTTP GET에 대해 테스트 하는 내용이 없습니다.

이 테스트 메소드 로직을 참고하셔서 여러분의 테스트 로직을 만들어 보라는 의미였어요.

2022-09-15 04:16 UTC, justinyoo requested changes

2022-09-15 04:16 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
>                  return new BadRequestResult();
혹시 여기가 `BadRequestResult` 가 맞나요? 헤더, 쿼리 유효성 검사를 한 결과를 통해서는 맞긴 할텐데, Invoke 메소드를 통해서 에러가 나온다면... BadRequestResult 보다는 InternalSeverError 같은 게 되어야 하지 않을까 싶습니다...?

2022-09-15 04:25 UTC, wnsgml7267 commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                request.Content = new StringContent(serialised, Encoding.UTF8, MediaTypeNames.Application.Json);
`Stringcontent` 는 문자열만 허용하고, `ObjectContent` 는 더 넓은 범위의 타입을 허용하는 것으로 이해를 했습니다.
현재 코드에서는 문자열만 전송하는 것으로 이해를 했는데, 문자열만 있더라도 ObjectContent를 사용해도 문제는 없는 것 같으나, stringcontent를 사용하는 것보다 어떤 부분에서 더 이점이 있는지 모르겠습니다.

2022-09-15 05:26 UTC, wnsgml7267 commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                             .Validate();
![image](https://user-images.githubusercontent.com/82314940/190319102-116143fe-6418-40e9-89f8-b9b5a5e2ed15.png)

`ConfigureAwait(false)` 를 붙이려고 하니 이러한 에러가 발생합니다.

`RequestHeaderValidator.cs` 에 있는 Validate Task 메소드를 수정해야 하나 싶어 시도해보고 다른 곳도 여럿 수정해봤지만 해결이 잘 되지 않아서 질문드립니다. 어떤 부분 때문에 에러가 발생하는지 잘 모르겠습니다.

2022-09-15 06:18 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                request.Content = new StringContent(serialised, Encoding.UTF8, MediaTypeNames.Application.Json);
StringContent 는 우리가 직렬화를 해서 넣어줘야 하고, ObjectContent 는 알아서 직렬화를 해 줍니다.

2022-09-15 06:23 UTC, wnsgml7267 commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                request.Content = new StringContent(serialised, Encoding.UTF8, MediaTypeNames.Application.Json);
아 그렇다면 ObjectContent를 사용하는 게 StringContent처럼 직렬화를 직접 해줄 필요가 없으니 더 편해서 사용하는 것인가요? 아니면 성능 면에서도 차이가 있나요??

2022-09-15 15:29 UTC, wnsgml7267 commented
엇 Modify Invoke Summary in HttpTriggerWorkflow 인데, 커밋 메세지를 잘못 날렸습니다. 죄송합니다!

2022-09-15 15:44 UTC, wnsgml7267 commented
```C#
[OpenApiResponseWithoutBody(statusCode: HttpStatusCode.BadRequest, Description = "The input was invalid")]
[OpenApiResponseWithoutBody(statusCode: HttpStatusCode.InternalServerError, Description = "The service has got an unexpected error")]
```
GetMessage에 예외 처리 부분 수정이 완료된다면, 해당 코드는 지워도 되는 거 맞을까요??

2022-09-16 22:46 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                             .Validate();
앗, 여기가 아니네? 미안해욥! 여긴 ConfigureAwait 붙이는 곳이 아니네 ㄷㄷㄷ

2022-09-16 22:48 UTC, justinyoo commented on src/nt-sms/Workflows/HttpTriggerWorkflow.cs
> +                request.Content = new StringContent(serialised, Encoding.UTF8, MediaTypeNames.Application.Json);
편한 것도 있지만, `ObjectContent` 를 사용하면 추가적인 `JsonMediaFormatter` 를 의존성 개체로 필요로 합니다. 그렇다면, 새로운 의존성 개체를 들이면서 편리함을 추구할 것인가, 아니면 내가 한줄 더 써서 의존성 개체를 줄일 것인가...

머 그런 고민이죠.

2022-09-16 22:51 UTC, justinyoo commented
> ```cs
> [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.BadRequest, Description = "The input was invalid")]
> [OpenApiResponseWithoutBody(statusCode: HttpStatusCode.InternalServerError, Description = "The service has got an unexpected error")]
> ```
> 
> GetMessage에 예외 처리 부분 수정이 완료된다면, 해당 코드는 지워도 되는 거 맞을까요??

예외 처리를 하면 삭제하는 대신 `OpenApiResponseWithBody` 바꿔야겠죠? 이제는 응답 개체가 생겼으니까?

2022-09-16 23:00 UTC, justinyoo requested changes

2022-09-16 23:00 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +            }
`RequestHeaderNotValidException`과 `RequestQueryNotValidException`은 둘 다 `ToastException`을 상속 받았으니, 이걸 하나로 퉁칠 수 있지 않을까요?

2022-09-16 23:00 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +                return new OkObjectResult(error);
혹시... 이건 제안인데, 지금 동일한 `ErrorMessageResponse`를 여러번 만들어 사용하잖아요? 이럴 때 리팩토링 하라고 했으니...

`ToastErrorObjectResult` 라는 걸 `OkObjectResult`를 상속 받아서 만들고, 거기에 exception 개체를 생성자 파라미터로 넣으면 그냥 알아서 다 되게 하는 식으로 바꾸는 게 많이 어려울까요?

이건 지금 당장 할 건 아니고, 다음번 PR에서 추가하면 좋겠네요.

2022-09-16 23:50 UTC, wnsgml7267 commented on src/nt-sms/Triggers/GetMessage.cs
> +                return new OkObjectResult(error);
그렇네요! 이 부분도 리팩토링이 필요한 것 같습니다!! 다음 PR 때 한 번 고민해보도록 하겠습니다.

2022-09-18 04:47 UTC, wnsgml7267 commented
```C#
        //쿼리 예외 테스트
        [TestMethod]
        public void Given_ValidQueries_fails_When_Invoke_ValidateQueriesAsync_Then_It_Should_Throw_Exception()
        {
            var queries = new QueryString();
            queries.Add("name","value");
            
            var req = new Mock<HttpRequest>();
            req.SetupGet(p => p.QueryString).Returns(queries);
            
            var validator = new Mock<IValidator<FakeRequestQueries>>();
            var workflow = new HttpTriggerWorkflow(this._factory.Object);
            Func<Task> func = async () => await workflow.ValidateQueriesAsync<FakeRequestQueries>(req.Object, validator.Object);

            func.Should().ThrowAsync<RequestQueryNotValidException>();
        }
```
쿼리 예외 테스트 코드를 작성 중에 질문이 있습니다.
해당 테스트를 돌리면, The active test run was aborted. Reason: Test host process crashed : Stack overflow. 라는 문구가 뜹니다.
`validator` 혹은 `queries` 가 잘못된 것 같은데, 정확한 원인을 모르겠습니다! 아니면 접근 방식 자체가 틀린건가요??

2022-09-18 08:21 UTC, wnsgml7267 commented
```C#
try
            {
                var paths = new GetMessageRequestPaths() {RequestId = requestId};
                var payload = await this._workflow.ValidateHeaderAsync(req)
                                                   .ValidateQueriesAsync(req, this._validator)
                                                   .BuildRequestUrlAsync(this._settings.Endpoints.GetMessage, this._settings, paths)
                                                   .InvokeAsync<GetMessageResponse>(HttpMethod.Get)
                                                   .ConfigureAwait(false);
                return new OkObjectResult(payload);
            }
```
제네릭 관련해서 질문이 있습니다!

`ValidateQueriesAsync(req, this._validator)`
`BuildRequestUrlAsync(this._settings.Endpoints.GetMessage, this._settings, paths)` 

서비스 레이어에서는 제네릭 메소드로 만들었는데, GetMessage에서 해당 메소드에 제네릭을 생성 안 해도 되는지 궁금합니다.

원래 생각했던 바, `ValidateQueriesAsync<GetMessageRequestQueries>(req, this._validator)` 이런 식으로 제네릭을 생성해야 하는 줄 알았는데, 샘플 코드에는 없어서 질문드립니다!

2022-09-18 08:56 UTC, justinyoo commented
> ```cs
>         //쿼리 예외 테스트
>         [TestMethod]
>         public void Given_ValidQueries_fails_When_Invoke_ValidateQueriesAsync_Then_It_Should_Throw_Exception()
>         {
>             var queries = new QueryString();
>             queries.Add("name","value");
>             
>             var req = new Mock<HttpRequest>();
>             req.SetupGet(p => p.QueryString).Returns(queries);
>             
>             var validator = new Mock<IValidator<FakeRequestQueries>>();
>             var workflow = new HttpTriggerWorkflow(this._factory.Object);
>             Func<Task> func = async () => await workflow.ValidateQueriesAsync<FakeRequestQueries>(req.Object, validator.Object);
> 
>             func.Should().ThrowAsync<RequestQueryNotValidException>();
>         }
> ```
> 
> 쿼리 예외 테스트 코드를 작성 중에 질문이 있습니다. 해당 테스트를 돌리면, The active test run was aborted. Reason: Test host process crashed : Stack overflow. 라는 문구가 뜹니다. `validator` 혹은 `queries` 가 잘못된 것 같은데, 정확한 원인을 모르겠습니다! 아니면 접근 방식 자체가 틀린건가요??

이게 레퍼런스를 계속 쫓아가 봐야 합니다. `req.SetupGet(p => p.QueryString).Returns(queries);` 요게 아니라 `req.SetupGet(p => p.Query).Returns(queries);` 쪽을 보셔야 해요.

그리고 결국 돌고 돌아서 아래 메소드를 참조하게 됩니다.

https://github.com/devrel-kr/nhn-toast-notification-service-custom-connector/blob/c3202f2684dce89b0577dc3a9d0d5e0c3e257f14/src/nt-sms/Validators/GetMessageRequestQueryValidator.cs#L21-L33

확인해 보세요.

2022-09-18 08:59 UTC, justinyoo commented
> ```cs
> try
>             {
>                 var paths = new GetMessageRequestPaths() {RequestId = requestId};
>                 var payload = await this._workflow.ValidateHeaderAsync(req)
>                                                    .ValidateQueriesAsync(req, this._validator)
>                                                    .BuildRequestUrlAsync(this._settings.Endpoints.GetMessage, this._settings, paths)
>                                                    .InvokeAsync<GetMessageResponse>(HttpMethod.Get)
>                                                    .ConfigureAwait(false);
>                 return new OkObjectResult(payload);
>             }
> ```
> 
> 제네릭 관련해서 질문이 있습니다!
> 
> `ValidateQueriesAsync(req, this._validator)` `BuildRequestUrlAsync(this._settings.Endpoints.GetMessage, this._settings, paths)`
> 
> 서비스 레이어에서는 제네릭 메소드로 만들었는데, GetMessage에서 해당 메소드에 제네릭을 생성 안 해도 되는지 궁금합니다.
> 
> 원래 생각했던 바, `ValidateQueriesAsync<GetMessageRequestQueries>(req, this._validator)` 이런 식으로 제네릭을 생성해야 하는 줄 알았는데, 샘플 코드에는 없어서 질문드립니다!

이건 신택스 슈가 같은 건데요, `this._validator` 인스턴스 타입이 이미 `IValidator<GetMessageRequestQueries>` 이거잖아요? 그러니까 중복으로 넣을 필요가 없어서 명시적으로 언급하지 않아도 됩니다. 이거 VS Code 익스텐션 깔면 그 부분이 흐릿하게 나와서 쉽게 알 수 있을 거예요.

2022-09-19 06:31 UTC, wnsgml7267 commented on src/nt-sms/Triggers/GetMessage.cs
> +            }
하나로 통합하기 위해  동일한 부모 클래스를 상속받는 것을 키워드로 해서 알아봤지만, 실제로 적용하는 방법에 대해 찾지 못하고, 어떤식으로 바꿔야 할 지 감을 못 잡아서 질문 드립니다.
```C#
            catch (ToastException ex)
            {
                var error = new ErrorMessageResponse();
                error.Header.IsSuccessful = false;
                error.Header.ResultCode = (int)ex.StatusCode;
                error.Header.ResultMessage = ex.Message;

                return new OkObjectResult(error);
            }
```
이런식으로 그냥 파라미터에 `ToastException` 을 넣으면 해결이 될까요?

동일한 클래스를 상속받는 각 엔드포인트마다 다른 파라미터 값은 서비스 레이어에서 제네릭을 통해 해결했다면, 동일한 엔드포인트에서 다른 예외 처리는 어떻게 하나로 통합할 수 있을지에 대한 고민을 해결하지 못한 것 같습니다!

2022-09-19 08:44 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +            }
한 번 해 보세요. 그리고 그걸 단위테스트로 돌려보면 되겠죠?

2022-09-19 16:46 UTC, wnsgml7267 commented on src/nt-sms/Triggers/GetMessage.cs
> +            }
잘 되는지 확인해보려면 임시로 예외가 잘 던져지는지 테스트하기 위한 단위테스트를 만들어야하는 걸로 이해하면 될까요?

2022-09-20 01:50 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +            }
임시로 단위테스트를 만드는게 아니라 그 역시도 단위테스트의 일부분입니다.

2022-09-20 01:53 UTC, justinyoo commented on src/nt-sms/Triggers/GetMessage.cs
> +            }
예외가 발생하는 상황에 대한 로직 처리 상황에서 `RequestHeaderNotValidException` 또는 `RequestQueryNotValidException `을 던지는데, 그걸 `ToastException`으로 받는지 확인해 봐야겠죠? 그리고, 모든 Unhandled exceptions 들은 `Exception`으로 받는 것도 확인해 봐야 할테구요.

이 모든 것들이 다 비지니스 로직에 포함되어 있으니, 단위테스트는 이 비지니스 로직이 제대로 돌아가는지 확인하는 목적으로 짜는 겁니다.

2022-09-20 06:44 UTC, wnsgml7267 commented
> > ```cs
> >         //쿼리 예외 테스트
> >         [TestMethod]
> >         public void Given_ValidQueries_fails_When_Invoke_ValidateQueriesAsync_Then_It_Should_Throw_Exception()
> >         {
> >             var queries = new QueryString();
> >             queries.Add("name","value");
> >             
> >             var req = new Mock<HttpRequest>();
> >             req.SetupGet(p => p.QueryString).Returns(queries);
> >             
> >             var validator = new Mock<IValidator<FakeRequestQueries>>();
> >             var workflow = new HttpTriggerWorkflow(this._factory.Object);
> >             Func<Task> func = async () => await workflow.ValidateQueriesAsync<FakeRequestQueries>(req.Object, validator.Object);
> > 
> >             func.Should().ThrowAsync<RequestQueryNotValidException>();
> >         }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 쿼리 예외 테스트 코드를 작성 중에 질문이 있습니다. 해당 테스트를 돌리면, The active test run was aborted. Reason: Test host process crashed : Stack overflow. 라는 문구가 뜹니다. `validator` 혹은 `queries` 가 잘못된 것 같은데, 정확한 원인을 모르겠습니다! 아니면 접근 방식 자체가 틀린건가요??
> 
> 이게 레퍼런스를 계속 쫓아가 봐야 합니다. `req.SetupGet(p => p.QueryString).Returns(queries);` 요게 아니라 `req.SetupGet(p => p.Query).Returns(queries);` 쪽을 보셔야 해요.
> 
> 그리고 결국 돌고 돌아서 아래 메소드를 참조하게 됩니다.
> 
> https://github.com/devrel-kr/nhn-toast-notification-service-custom-connector/blob/c3202f2684dce89b0577dc3a9d0d5e0c3e257f14/src/nt-sms/Validators/GetMessageRequestQueryValidator.cs#L21-L33
> 
> 확인해 보세요.

![image](https://user-images.githubusercontent.com/82314940/191185895-b49583b4-dccb-447e-8fdf-0d94b1306ba3.png)

처음에 `req.SetupGet(p => p.Query).Returns(queries);` 로 시도를 해봤었는데, 해당 에러를 해결하지 못했었습니다. queries에 생성자 부분이 잘못됐나 싶어 찾아봤지만, 오류 해결에 실패해서 어떤식으로 바꿔야할지 잘 모르겠습니다..!

2022-09-23 08:01 UTC, justinyoo requested changes
테스트 코드를 추가하면 되겠군요!

2022-09-24 17:06 UTC, wnsgml7267 commented
단위테스트는 리뷰받고 싶을 때 테스트 실패한 상태로 커밋해도 되나요?? 안된다면 주석처리 하도록 하겠습니다..!

2022-09-25 09:53 UTC, justinyoo commented
> 단위테스트는 리뷰받고 싶을 때 테스트 실패한 상태로 커밋해도 되나요?? 안된다면 주석처리 하도록 하겠습니다..!

테스트 코드 자체는 빌드를 통과해야 합니다. 실패한 경우를 테스트 하고 싶다는 의미인가요? 아니면 코드 자체가 빌드가 실패해도 괜찮냐는 의미인가요?

2022-09-25 14:24 UTC, wnsgml7267 commented
> > 단위테스트는 리뷰받고 싶을 때 테스트 실패한 상태로 커밋해도 되나요?? 안된다면 주석처리 하도록 하겠습니다..!
> 
> 테스트 코드 자체는 빌드를 통과해야 합니다. 실패한 경우를 테스트 하고 싶다는 의미인가요? 아니면 코드 자체가 빌드가 실패해도 괜찮냐는 의미인가요?

빌드는 성공하는데, 작성하고 있는 단위 테스트가 실패해서 CI/CD 파이프라인이 실패할 것 같은 상황에서 입니다!

2022-09-26 00:37 UTC, justinyoo commented
> > > 단위테스트는 리뷰받고 싶을 때 테스트 실패한 상태로 커밋해도 되나요?? 안된다면 주석처리 하도록 하겠습니다..!
> > 
> > 
> > 테스트 코드 자체는 빌드를 통과해야 합니다. 실패한 경우를 테스트 하고 싶다는 의미인가요? 아니면 코드 자체가 빌드가 실패해도 괜찮냐는 의미인가요?
> 
> 빌드는 성공하는데, 작성하고 있는 단위 테스트가 실패해서 CI/CD 파이프라인이 실패할 것 같은 상황에서 입니다!



> > > 단위테스트는 리뷰받고 싶을 때 테스트 실패한 상태로 커밋해도 되나요?? 안된다면 주석처리 하도록 하겠습니다..!
> > 
> > 
> > 테스트 코드 자체는 빌드를 통과해야 합니다. 실패한 경우를 테스트 하고 싶다는 의미인가요? 아니면 코드 자체가 빌드가 실패해도 괜찮냐는 의미인가요?
> 
> 빌드는 성공하는데, 작성하고 있는 단위 테스트가 실패해서 CI/CD 파이프라인이 실패할 것 같은 상황에서 입니다!

작성하고 있는 단위테스트가 실패한다는 의미가...

1. 실패 케이스를 테스트 한다는 것인지요?
2. 단위테스트를 통과하지 못한다는 것인지요?

두번째 경우라면 단위테스트를 통과하게끔 테스트 코드를 작성해야겠지요? 그래야 여러분이 리팩토링한 결과를 검증할 수 있으니까요. 코드 변경은 이 테스트 케이스까지 포함하셔야 합니다. 제가 보여드린 샘플 테스트 코드를 잘 확인해 보세요.

2022-09-26 00:40 UTC, wnsgml7267 commented
> > > > 단위테스트는 리뷰받고 싶을 때 테스트 실패한 상태로 커밋해도 되나요?? 안된다면 주석처리 하도록 하겠습니다..!
> > > 
> > > 
> > > 테스트 코드 자체는 빌드를 통과해야 합니다. 실패한 경우를 테스트 하고 싶다는 의미인가요? 아니면 코드 자체가 빌드가 실패해도 괜찮냐는 의미인가요?
> > 
> > 
> > 빌드는 성공하는데, 작성하고 있는 단위 테스트가 실패해서 CI/CD 파이프라인이 실패할 것 같은 상황에서 입니다!
> 
> > > > 단위테스트는 리뷰받고 싶을 때 테스트 실패한 상태로 커밋해도 되나요?? 안된다면 주석처리 하도록 하겠습니다..!
> > > 
> > > 
> > > 테스트 코드 자체는 빌드를 통과해야 합니다. 실패한 경우를 테스트 하고 싶다는 의미인가요? 아니면 코드 자체가 빌드가 실패해도 괜찮냐는 의미인가요?
> > 
> > 
> > 빌드는 성공하는데, 작성하고 있는 단위 테스트가 실패해서 CI/CD 파이프라인이 실패할 것 같은 상황에서 입니다!
> 
> 작성하고 있는 단위테스트가 실패한다는 의미가...
> 
> 1. 실패 케이스를 테스트 한다는 것인지요?
> 2. 단위테스트를 통과하지 못한다는 것인지요?
> 
> 두번째 경우라면 단위테스트를 통과하게끔 테스트 코드를 작성해야겠지요? 그래야 여러분이 리팩토링한 결과를 검증할 수 있으니까요. 코드 변경은 이 테스트 케이스까지 포함하셔야 합니다. 제가 보여드린 샘플 테스트 코드를 잘 확인해 보세요.

두번째 경우입니다! 네, 알겠습니다!!

2022-11-18 15:52 UTC, justinyoo commented
@wnsgml7267 우선은 닫아두고 나중에 다시 리뷰하겠습니다!

2022-11-18 15:52 UTC, closed without merging